experiment_name: decay_45000
dt: 0.0001
num_iters: 5000000
checkpoint_frequency: 1000
path_to_initial: olddata/solution_32768_alpha=0.1.npy
lambda: 0.05
final_lambda: 0.005
lambda_decay_type: logistic
alpha: 0.9
