# Name of the experiment. Will be used to store results.
experiment_name: decay_45000

# A numerical simulation timestep. Kept constant throughout simulation.
dt: 0.0001

# Total number of iterations done by simulation.
num_iters: 5000000

# How often to save results. Solutions will be saved every `checkpoint_frequency` iterations.
# Final solution is always saved.
checkpoint_frequency: 1000

# How many equations to use in the simulations. Monodisperse initial condition will be used, unless
# `path_to_initial` is specified.
# num_equations: 1000

# Path to initial condition. Initial condition should be a 1D numpy array in a binary format.
# The program uses 1-based indexing for the solution, so the concentration of clusters of size 1 should be
# stored at index 1. Index 0 is unused.
path_to_initial: olddata/solution_32768_alpha=0.1.npy


# Rate of cluster fragmenation in Smoluchowski equations.
lambda: 0.05

# Value of `lambda` at the end of experiment. Changes according to
# `lambda_decay_type` scheme. If omitted, lambda stays constant for the whole experiment.
final_lambda: 0.005

# Either exponential or logistic.
lambda_decay_type: exponential

# Brownial coagulation kernel parameter: K(i, j) = (i / j)**(alpha) + (j / i)**(alpha)
alpha: 0.9
